# Generated by Django 5.0.6 on 2025-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Clave del curso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel', models.IntegerField(verbose_name='Nivel de dificultad')),
                ('publicado', models.BooleanField(verbose_name='¿Publicado?')),
                ('categoria', models.CharField(choices=[('web', 'Web'), ('data', 'Datos'), ('ai', 'Inteligencia Artificial'), ('seg', 'Ciberseguridad')], max_length=50, verbose_name='Categoría')),
                ('portada', models.ImageField(upload_to='cursos/', verbose_name='Imagen de portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
